project:
  type: book

execute:
  freeze: true

book:
  title: "Tidy R programming with the OMOP common data model"
  author: "Edward Burn, Adam Black, Berta Raventós, Yuchen Guo, Mike Du, Kim López Güell, Núria Mercadé Besora, Martí Català Sabaté"
  date: today
  chapters:
  - index.qmd
  - ch_1_getting_started.qmd
  - ch_2_cdm_reference.qmd
  - ch_3_exploring_the_cdm.qmd
  - ch_4_adding_features.qmd
  - ch_5_creating_cohorts.qmd
  - ch_6_working_with_cohorts.qmd
  - ch_7_summarising_cohorts.qmd
  - ch_8_comparing_cohorts.qmd
  - ch_9_organising_study_code.qmd
  - ch_10_efficient_study_code.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


  
