project:
  type: book

book:
  title: "Tidy R programming with databases: applications with the OMOP common data model"
  author: "Edward Burn, Adam Black, Berta Raventós, Yuchen Guo, Mike Du, Kim López-Güell, Núria Mercadé-Besora, Martí Català"
  date: today
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - working_with_databases_from_r.qmd
        - tidyverse_verbs.qmd
        - tidyverse_expressions.qmd
        - dbplyr_packages.qmd
    - part: omop.qmd
      chapters: 
        - cdm_reference.qmd
        - exploring_the_cdm.qmd     
        - creating_cohorts.qmd
        - adding_features.qmd
        - working_with_cohorts.qmd
        - summarising_cohorts.qmd
        - comparing_cohorts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    output-file: "book"
    output-ext:  "pdf"
    
editor: visual