project:
  type: book
  output-dir: "_site"

book:
  title: "Tidy R programming with the OMOP Common Data Model"
  author:
    - name: Edward Burn
    - name: Adam Black
    - name: Berta Raventós
    - name: Yuchen Guo
    - name: Mike Du
    - name: Kim López-Güell
    - name: Núria Mercadé-Besora
    - name: Martí Català
  date: today
  chapters:
    - index.qmd
    - part: tidy_databases/index.qmd
      chapters: 
        - tidy_databases/working_with_databases.qmd
        - tidy_databases/tidyverse_verbs.qmd
        - tidy_databases/tidyverse_expressions.qmd
        - tidy_databases/data_model.qmd
    - part: omop/index.qmd
      chapters: 
        - omop/cdm_reference.qmd
        - omop/exploring_the_cdm.qmd   
        - omop/adding_features.qmd  
        - omop/creating_cohorts.qmd
        - omop/working_with_cohorts.qmd
    - final_remarks.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    citations: true
    link-citations: true
    code-tools: true
    code-link: true
  titlepage-pdf:
    titlepage: formal
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true
