project:
  type: book

book:
  title: "Tidy R programming with the OMOP common data model"
  author: "Edward Burn, Adam Black, Berta Raventós, Yuchen Guo, Mike Du, Kim López-Güell, Núria Mercadé-Besora, Martí Català"
  date: today
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - working_with_databases_from_r.qmd
        - tidyverse_verbs.qmd
        - tidyverse_expressions.qmd
    - part: explore.qmd
      chapters: 
        - cdm_reference.qmd
        - omop_person_obs_period.qmd
        - omop_vocabularies.qmd
        - omop_clinical_tables.qmd
    - part: data_analysis.qmd
      chapters: 
        - exploring_the_cdm.qmd
        - creating_cohorts.qmd
        - adding_features.qmd
        - working_with_cohorts.qmd
        - summarising_cohorts.qmd
        - comparing_cohorts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual