project:
  type: book
  output-dir: "_site"

book:
  title: "Tidy R programming with databases: applications with the OMOP common data model"
  author:
    - name: Edward Burn
    - name: Adam Black
    - name: Berta Raventós
    - name: Yuchen Guo
    - name: Mike Du
    - name: Kim López-Güell
    - name: Núria Mercadé-Besora
    - name: Martí Català
  date: today
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - working_with_databases_from_r.qmd
        - tidyverse_verbs.qmd
        - tidyverse_expressions.qmd
        - dbplyr_packages.qmd
    - part: omop.qmd
      chapters: 
        - cdm_reference.qmd
        - exploring_the_cdm.qmd   
        - adding_features.qmd  
        - creating_cohorts.qmd
        - working_with_cohorts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  titlepage-pdf:
    titlepage: formal
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true

editor: visual