project:
  type: book

execute:
  freeze: true

book:
  title: "Tidy R programming with data in databases: applications with the OMOP common data model"
  author: "Edward Burn, Adam Black, Marti Catala, Berta Raventós"
  date: today
  chapters:
    - index.qmd
    - getting_started_with_r.qmd
    - connecting_to_cdm.qmd
    - exploring_the_cdm.qmd
    - databases_and_r.qmd
    - strings.qmd
    - dates.qmd
    - working_with_multiple_tables.qmd
    - moving_to_arrow_and_r.qmd
    - analysis_in_r.qmd
    - other.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


  
