project:
  type: book

book:
  title: "Tidy R programming with the OMOP common data model"
  author: "Edward Burn, Adam Black, Berta Raventós, Yuchen Guo, Mike Du, Kim López-Güell, Núria Mercadé-Besora, Martí Català"
  date: today
  chapters:
  - index.qmd
  - ch_1_getting_started.qmd
  - ch_2_cdm_reference.qmd
  - ch_3_exploring_the_cdm.qmd
  - ch_4_adding_features.qmd
  - ch_5_creating_cohorts.qmd
  - ch_6_working_with_cohorts.qmd
  - ch_7_summarising_cohorts.qmd
  - ch_8_comparing_cohorts.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual
